version: 'minty.abcxyz.dev/v2'

rule:
  if: |-
    assertion.iss == 'https://token.actions.githubusercontent.com' &&
    assertion.repository_owner_id == '93787867' &&
    assertion.repository_id == '756991782'

scope:
  create-tag:
    rule:
      if: |-
        assertion.job_workflow_ref == "abcxyz/pkg/.github/workflows/create-tag.yml@refs/heads/main" &&
        assertion.workflow_ref.startsWith("abcxyz/containertest/.github/workflows/release.yml") &&
        assertion.ref == 'refs/heads/main' &&
        assertion.event_name == 'workflow_dispatch'
    repositories:
      - 'containertest'
    permissions:
      contents: 'write'
